import type { Review } from "@/types/review";

export const reviews: Review[] = [
  {
    id: "5387",
    productId: "180",
    name: "Noah T.",
    email: "noah.t@example.com",
    ratingStar: 5,
    desc: "The color and fabric quality are excellent. The fit is exactly what I expected from the size chart.",
    createdAt: "2026-03-18",
    isVerified: true,
  },
  {
    id: "5380",
    productId: "180",
    name: "Ava H.",
    email: "ava.h@example.com",
    ratingStar: 3.5,
    desc: "Good design overall, but I wish the waist had a bit more flexibility for movement.",
    createdAt: "2026-03-18",
    isVerified: true,
  },
  {
    id: "5374",
    productId: "180",
    name: "Samantha D.",
    email: "samantha.d@example.com",
    ratingStar: 4.5,
    desc: "Material feels premium and breathable. Works really well with sneakers and overshirts.",
    createdAt: "2026-03-17",
    isVerified: true,
  },
  {
    id: "5329",
    productId: "179",
    name: "Ethan R.",
    email: "ethan.r@example.com",
    ratingStar: 4,
    desc: "Nice shirt for office days. Sleeves are slightly long for me but still comfortable.",
    createdAt: "2026-03-15",
    isVerified: true,
  },
  {
    id: "5284",
    productId: "171",
    name: "Olivia P.",
    email: "olivia.p@example.com",
    ratingStar: 2.5,
    desc: "The tee looks good, but the color faded a little after two washes.",
    createdAt: "2026-03-10",
    isVerified: false,
  },
  {
    id: "5241",
    productId: "162",
    name: "Liam K.",
    email: "liam.k@example.com",
    ratingStar: 4.5,
    desc: "Clean tailoring and strong shoulder structure. Great value for a blazer in this range.",
    createdAt: "2026-03-06",
    isVerified: true,
  },
  {
    id: "5391",
    productId: "180",
    name: "Lucas M.",
    email: "lucas.m@example.com",
    ratingStar: 4,
    desc: "Comfortable for daily wear. The stitching looks solid and hasn’t shown any signs of wear yet.",
    createdAt: "2026-03-19",
    isVerified: true,
  },
  {
    id: "5392",
    productId: "180",
    name: "Mia L.",
    email: "mia.l@example.com",
    ratingStar: 5,
    desc: "Absolutely love the fit! It hugs the body nicely without feeling too tight.",
    createdAt: "2026-03-19",
    isVerified: true,
  },
  {
    id: "5393",
    productId: "180",
    name: "James W.",
    email: "james.w@example.com",
    ratingStar: 4.5,
    desc: "Very versatile piece. Works well for both casual and slightly formal outfits.",
    createdAt: "2026-03-18",
    isVerified: true,
  },
];
