export const UI_TEXT = {
  ORDER_PLACED_SUCCESS: "Order placed successfully. We will process it shortly.",
  ORDER_PLACED_SUCCESS_LONG: "Your order has been placed successfully. We will process it shortly.",
  REVIEW_SUBMIT_SUCCESS_TOAST: "Review submitted successfully. Thank you for your feedback!",
  REVIEW_SUBMITTING: "Submitting review...",
  REVIEW_SUBMITTED: "Review submitted successfully.",
  ITEM_ADDED_TO_CART: "Item added to cart",
  BACK_ONLINE: "Back online",
  NO_INTERNET_CONNECTION: "No internet connection",
  ORDER_SUMMARY: "Order Summary",
  SUBTOTAL: "Subtotal",
  DISCOUNT: "Discount",
  DELIVERY_FEE: "Delivery Fee",
  TOTAL: "Total",
  GO_TO_CHECKOUT: "Go to Checkout",
  BACK_TO_HOME: "Back to Home",
  GO_BACK_TO_HOME: "Go back to Home",
  TRY_AGAIN: "Try Again",
  PRODUCT_NOT_FOUND: "Product not found.",
  LOADING: "Loading",
} as const;
